### ISSUE TITLE
Inconsistent id prefix for hexmaps

### ISSUE THREAD

**Issue by dospunk** [slowe/stuquery#2]
On line 36 of stuquery.hexmap.js the id prefix for the HexMap function is listed as "hex-", but in the page you've used "hexmap-" as the id prefix

**Comment by slowe** [comment]
@dospunk Sorry for not seeing this comment earlier (I keep missing notifications for some reason). The `idprefix` property in `stuquery.hexmap.js` was used at one point but is no longer used. I'll remove it.
