### ISSUE TITLE
Bugs on the example homepage (https://slowe.github.io/stuquery/hexmap.html)

### ISSUE THREAD

**Issue by ok-ttc** [slowe/stuquery#5]
Hello,

I love the concept of this project. I just want to point out, that some examples on the homepage (https://slowe.github.io/stuquery/hexmap.html) do not work due to JS errors. Specifically it is

- [Settling hex island](https://slowe.github.io/stuquery/hexmap.html) -> Randomizing does not work and lower left hex does not render correctly
- [London 1985](https://slowe.github.io/stuquery/hexmap.html) -> Hex 1a's text does not align well
- [Hex map from HTML elements](https://slowe.github.io/stuquery/hexmap.html#html) -> is listed twice. IS the page end possibly broken?

I would love to see these functional as well. :-)

Good work with this project!

**Comment by slowe** [comment]
@ok-ttc Sorry for the long time it has taken for me to notice this issue. Thanks for spotting these. I've hopefully fixed them.
